### PR TITLE
Update Backend to Spring Boot 3

### LINKED ISSUE #23: Update Backend code to Spring 3
In this issue, we'll update the backend code to Spring 3

# Why we need to do this.

* Security; some of the dependencies we are using have security issues that are only patched in Spring 3.  (This is the main reason)
* Features; Spring 3 has some capabilities that are not present in Spring 2. (At moment, none of them are critical, but it would be better to be on the version of Spring that is getting more updates.)

# How to do it

This PR shows how we updated the code base for STARTER-team03 to Spring 3.  It is likely that if you do the exact same things, it will work for this code base:

* <https://github.com/ucsb-cs156-f24/STARTER-team03/pull/13>

# Notes

* Q: Do I need the aop class that is in the STARTER-team03 code?
  * A: No, it's not necessary. However, that's also a nice thing to add, and we'll make a separate issue for that.
* Q: The STARTER-team03 has code for integration and end2end tests.  Do we need to add those in this issue?
  * A: No.  However, adding the lines in the pom.xml that exclude those from pitest is still a good idea, since those might get added into the code base in the future.

### PR DESCRIPTION
**Pull request by gracefeng05**
In this PR, I updated the backend code to Spring Boot 3.2.1 by following how it was done for [Team03](https://github.com/ucsb-cs156-f24/STARTER-team03/pull/13). I worked through the import statements by replacing instances of `javax` with `jakarta`, while ensuring that all tests still passed along the way.

Updating the backend to Spring 3 increases security and adds capabilities.

Deployment Link: [https://gauchoride-gracefeng05-dev.dokku-15.cs.ucsb.edu](https://gauchoride-gracefeng05-dev.dokku-15.cs.ucsb.edu)

Closes #23

### CODE REVIEW

**Review by zhenbi93 — DISMISSED** [review]
LGTM, 
截屏2024-05-27 下午10 56 24

**Review by pconrad — CHANGES_REQUESTED** [review]
I think you might also need to remove this line from `application-production.properties` per the discussion in the slack channel here:

https://ucsb-cs156-s24.slack.com/archives/C074MLEP1QD/p1716436359312639

```
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
```

**Comment by gracefeng05** [comment]
> I think you might also need to remove this line from `application-production.properties` per the discussion in the slack channel here:
> 
> https://ucsb-cs156-s24.slack.com/archives/C074MLEP1QD/p1716436359312639
> 
> ```
> spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL9Dialect
> ```

Removed the line!

**Review by pconrad — APPROVED** [review]
LGTM

**Pull request merged**
